### ISSUE TITLE
USER STORY: Create Posts

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#11]
As a **registered user** I can **create and share my own posts** so that **all of my followers can see what i'm up to!**

## Acceptance Criteria 

- A signed in user can create a post adding an image, caption and category and it will display on the site as well as being stored in the backend API. 

## Tasks 

- [x] Create createPostForm.js with post creation fields
- [x] Define handleChange, handleSubmit and handleChangeImage functions
- [x] Make an axiosReq.post request to save the post to the api

**Comment by dantaylor28** [comment]
Completed
