### ISSUE TITLE
USER STORY: Pin Posts

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#12]
In order to **show my appreciation for posts and save them for later** as a **registered user**, I can **pin a post from any of the sites users.**

## Acceptance Criteria 

- Users can click a button to pin or unpin a post and those changes will be reflected in the backend API. 

## Tasks 

- [x] Define handlePin function which make an axiosRes post request and increments num_of_pins by 1
- [x] Define the handleUnpin which makes a delete request and decrements num_of_pins by 1
- [x] Add a pin/unpin button and add an onclick attribute with a value of my defined functions

**Comment by dantaylor28** [comment]
Completed
