### ISSUE TITLE
USER STORY: Open a Post

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#13]
As a **site user** I can **click on a post to see it in its entirety** so that **I can learn more about it and pin it if I wish.**

## Acceptance Criteria

- Clicking on a post opens it fully on another page and displays a larger image along with any comments the post has.

## Tasks 

- [x] Create PostDetail page along with a post component 
- [x] Destructure all post data as required props and make an axiosReq.post request to /posts/${id}
- [x] Return a bootstrap card element displaying all the relevant post data to the user

**Comment by dantaylor28** [comment]
Completed
