### ISSUE TITLE
USER STORY: Infinite Scroll

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#16]
In order to **make it as easy as possible to view content** as a **site user**, I can **scroll down the page and more posts will load for me automatically.**

## Acceptance Criteria 

- Users can scroll down through posts and comments, and content will continue to be loaded for them to view.

## Tasks 

- [x] Install react-infinite-scroll-component
- [x] Auto import it and add required attributes - children, dataLength, loader, hasMore & next
- [x] Define getMoreData in utils.js and make a get request for more resources eg posts, setPosts
- [x] Add and call getMoreData in the next attribute

**Comment by dantaylor28** [comment]
Completed
