### ISSUE TITLE
USER STORY: Search Bar

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#17]
As a **site user** I can **filter through posts by searching users, categories or keywords** so that **I can quickly and easily find a post or profile that I am looking for.**

## Acceptance Criteria

- A search bar is present on the site
and can be used to filter posts by user, title, bio and category.

## Tasks 

- [x] Create a search bar using a bootstrap Form component 
- [x] Destructure searchQuery and setSearchQuery and apply a value and onChange value to the Form.Control
- [x] Call the setSearchQuery function with event.target.value in the onChange attribute and add the search={searchQuery onto the end of the axios.get request

**Comment by dantaylor28** [comment]
Completed
