### ISSUE TITLE
USER STORY: Read User Comments

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#19]
As a **site user** I can **click on a post and be taken to the post page** so that **I can read any comments that have been left by other users.**

## Acceptance Criteria

- A list of all user comments are visible to read regardless of a user's logged in status.

## Tasks 

- [x] Create the Comment.js component used to display the comments to the user
- [x] Make an axiosReq.get request on PostDetail.js to request all the user comments for a post via  the post.id
- [x] Map over all of the comments in PostsDetail.js and call the Comment component to render all comments to the page

**Comment by dantaylor28** [comment]
Completed
