### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#2]
As a **site user** I can **sign up for an account** so that **I can access all of the signed in functionality of the site.**

## Acceptance Criteria 

- A user can create an account and their account details will be saved to the backend API and they can successfully sign in.

## Tasks 

- [x] Create a signup form with user registration form fields.
- [x] Define handleChange and handleSubmit functions.
- [x] Make a post request to dj-rest-auth/registration/ endpoint

**Comment by dantaylor28** [comment]
Completed
