### ISSUE TITLE
USER STORY: Post Comments

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#20]
In order to **interact with the content and share my thoughts** as a **registered user**, I can **leave comments on posts.**

## Acceptance Criteria

- Signed in users can leave comments on a post and they will display directly underneath it with the comments author and a timestamp.

## Tasks 

- [x] Create a comment form input component 
- [x] Define a handleChange and handleSubmit function and add to the comment form onChange and onSubmit variables
- [x] Make an axiosRes.post request to the api to store the comment in the database

**Comment by dantaylor28** [comment]
Completed
