### ISSUE TITLE
USER STORY: Like User Comments

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#21]
As a **registered user** I can **like other users comments** so that **I can show my support for the comment that they are making.**

## Acceptance Criteria

- Users can click an icon next to each comment to like it and then have that like saved to the database on the backend API.

## Tasks 

- [x] Display a thumbs up font awesome icon inside a button next to all comments with the "num_of_comment_likes" variable next to it
- [x] Define the handleCommentLike and handleCommentUnlike functions to increment or decrement the num_of_comment_likes accordingly
- [x] Make a post/delete request to the "comments/likes" endpoint

**Comment by dantaylor28** [comment]
Completed
