### ISSUE TITLE
USER STORY: Edit Comments

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#22]
As a **comment owner** I can **edit my comments** so that **I can amend any mistakes or update the text I wish to share.**

## Acceptance Criteria

- Users can click an edit button to make their comment available to edit and these changes will reflect on the front and backend.

## Tasks 

- [x] Create EditCommentForm.js and paste in the same code from CreateCommentForm
- [x] Add the DisplayEditForm and setEditFormDisplay with a boolean value that changes to true when the edit button is clicked
- [x] Define the handleSubmit function which makes an axiosRes.put request to the server with the updated comment
- [x] Have the function called and DisplayProfileForm set back to false when the new comment is submitted

**Comment by dantaylor28** [comment]
Completed
