### ISSUE TITLE
USER STORY: Delete Comments

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#23]
As a **comment owner** I can **delete my comments** so that **I have the freedom to decide what I would or would not like to share.**

## Acceptance Criteria

- Comments belonging to the current user can be deleted from the frontend and these changes will be reflected on the backend.

## Tasks 

- [x] Add my EditDeleteDropdown component to the comments a user owns 
- [x] Define the handleDelete function that makes an axiosRes.delete request with the comment id passed into it 
- [x] Filter out the comment and decrement the num_of_comments by 1
- [x] Assign the handleDelete function to the handleDelete prop in the dropdown component

**Comment by dantaylor28** [comment]
Completed
