### ISSUE TITLE
USER STORY: Delete My Posts

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#26]
As a **post owner** I can **delete my posts** so that **I have the freedom to decide on what I would or would not like to share.**

## Acceptance Criteria 

- Posts belonging to the currently signed in user can be deleted and that deletion will happen on both the frontend and backend API.

## Tasks

- [x] Add delete button for user if they are the owner of the post
- [x] Define the handleDelete function and make an axiosRes.delete request to the api passing in the post_id
- [x] Call that function in the onClick attribute of the delete button

**Comment by dantaylor28** [comment]
Completed
