### ISSUE TITLE
USER STORY: Visit User Profiles

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#27]
As a **site user** I can **visit other users profile pages** so that **I can learn more about them and see what posts they have shared.**

## Acceptance Criteria 

- Users can click an avatar and be redirected to that specified users profile page with their profile details.

## Tasks 

- [x] Create ProfilePage.js showcasing a users profile details and stats
- [x] Make a get request to the "/posts/?owner__profile=${id}" endpoint to get every post for the owner of each specific profile
- [x] Give every profile avatar a link redirecting them to that users profile

**Comment by dantaylor28** [comment]
Completed
