### ISSUE TITLE
USER STORY: Follow/Unfollow Profiles

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#29]
As a **registered user** I can **follow or unfollow a profile** so that **I can show support to their page and keep up to date on what they share.**

## Acceptance Criteria

-  Users can press the follow/unfollow button and their following/followers count will update accordingly while the followers database on the backend will reflect these changes.

## Tasks 

- [x] Define a follow and unfollowHelper to either increase or decrease the following/followers count by 1 in Utils.js
- [x] Define a handleFollow and handleUnfollow function ProfilePage.js
- [x] Make a post and delete request as well as calling the appropriate follow helper function within each handle function

**Comment by dantaylor28** [comment]
Completed
