### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#3]
As a **registered user** I can **sign into my account** so that **I can access all of my posts and see what my followers are sharing.**

## Acceptance Criteria 

- Users can sign into their account and have access to all of the features of a signed in user. 

## Tasks 

- [x] Create a sign in form with required form fields
- [x] Define handleChange and handleSubmit functions 
- [x] Make a post request to dj-rest-auth/login/ and save sign in data to signInData variable

**Comment by dantaylor28** [comment]
Completed
