### ISSUE TITLE
USER STORY: Customise Own Profile

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#30]
As a **registered user** I can **edit my profile page** so that **I can customise it with a profile image, a bio and my location.**

## Acceptance Criteria

- The user can navigate to an edit page, update their profile picture, bio and location, and those changes will then be reflected on their own profile page.

## Tasks 

- [x] Create EditProfileForm.js with a form to update the profile details
- [x] Define my handleSubmit function with the new appended formData
- [x] Make a put request to the "profiles/${id}" endpoint

**Comment by dantaylor28** [comment]
Completed
