### ISSUE TITLE
USER STORY: Update Username & Password

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#31]
As a **registered user** I can **update my username and password** so that **I can keep my page secure and update my display name.**

## Acceptance Criteria

- Users can access an EditProfile form where they can change their username and password. Any changes will be present after form submission.

## Tasks 

- [x] Create UsernameForm and PasswordForm.js with a form to update each and a handleSubmit function
- [x] Make a put request to the "dj-rest-auth/user/" endpoint to update the username
- [x] Make a post request to the "dj-rest-auth/password/change/" to change the password

**Comment by dantaylor28** [comment]
Completed
