### ISSUE TITLE
USER STORY: Popular Profiles List

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#32]
In order to **discover new profiles to follow** as a **registered user**, I can **see a list of the most popular profiles on the site.**

## Acceptance Criteria

- A list of the ten most followed profiles are present on the site ordered from the most followers to the least.

## Tasks 

- [x] Create MostFollowedProfiles.js
- [x] Make an API request for the 10 most followed profiles
- [x] Code a most followed div to contain the list of profiles
- [x] Display each profile in the ProfileAvatar component with their display name and a follow/unfollow button next to each

**Comment by dantaylor28** [comment]
Completed
