### ISSUE TITLE
USER STORY: Logout

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#5]
As a **registered user**, when signed in I can **access the logout button in the navbar** so that **I can click it and sign out of my account with ease.**

## Acceptance Criteria 

- A user can press the sign out button and be successfully logged out of their account.

## Tasks 

- [x] Add sign out button to the navbar.
- [x] Conditionally render it for signed in users.
- [x] Add functionality to sign users out when the button is clicked.

**Comment by dantaylor28** [comment]
Completed
