### ISSUE TITLE
USER STORY: Conditionally Rendered Navbar

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#6]
As a **registered user** I can **see the navbar conditionally render between the features of a logged in user versus a logged out one** so that **I am continuously aware of my logged in status.**

## Acceptance Criteria 

- The NavBar displays the correct links when a user is signed in or signed out.

## Tasks 

- [x] Request data from api showing current user.
- [x] Create current user context provider.
- [x] Render specific links depending on if a current user exists.

**Comment by dantaylor28** [comment]
Completed
