### ISSUE TITLE
USER STORY: Display Avatars/Usernames

### ISSUE THREAD

**Issue by dantaylor28** [DanTaylor28/pp5-social-media-frontend#8]
As a **site user** I can **view different users display names and avatars** so that **the profile owner can be easily identified.**

## Acceptance Criteria 

- Every user profile has an avatar displaying their profile image and links to their profile page when clicked.

## Tasks 

- [x] Create a profileAvatar component within an image tag containing props including src, size and text
- [x] Import this component where i want to show an avatar and set src as my required profile_image
- [x] Wrap it in a link tag that will take you to the associated profile when clicked

**Comment by dantaylor28** [comment]
Completed
